# frozen_string_literal: true

module DesignationEnum
  extend ActiveSupport::Concern

  included do
    enum designation: {
      associate_software_engineer: 'Associate Software Engineer',
      software_engineer: 'Software Engineer',
      senior_software_engineer: 'Senior Software Engineer',
      associate_tech_lead: 'Associate Tech Lead',
      tech_lead: 'Tech Lead',
      senior_tech_lead: 'Senior Tech Lead',
      associate_architect: 'Associate Architect',
      architect: 'Architect',
      senior_architect: 'Senior Architect',
      development_manager: 'Development Manager',
      senior_development_manager: 'Senior Development Manager',
      staff_software_engineer: 'Staff Software Engineer',
      senior_staff_software_engineer: 'Senior Staff Software Engineer',
      principle_software_engineer: 'Principle Software Engineer',
      senior_principle_software_engineer: 'Senior Principle Software Engineer',
      CTO: 'CTO',
      associate_qa_engineer: 'Associate QA Engineer',
      qa_engineer: 'QA Engineer',
      senior_qa_engineer: 'Senior QA Engineer',
      associate_qa_lead: 'Associate QA Lead',
      qa_lead: 'QA Lead',
      senior_qa_lead: 'Senior QA Lead',
      associate_qa_architect: 'Associate QA Architect',
      qa_architect: 'QA Architect',
      senior_qa_architect: 'Senior QA Architect',
      product_manager: 'Product Manager',
      senior_product_manager: 'Senior Product Manager',
      business_analyst: 'Business Analyst',
      senior_business_analyst: 'Senior Business Analyst',
      associate_ui_ux_engineer: 'Associate UI/UX Engineer',
      ui_ux_engineer: 'UI/UX Engineer',
      senior_ui_ux_engineer: 'Senior UI/UX Engineer',
      lead_ui_ux_engineer: 'Lead UI/UX Engineer',
      senior_lead_ui_ux_engineer: 'Senior Lead UI/UX Engineer',
      ui_ux_architect: 'UI/UX Architect',
      ui_ux_senior_architect: 'UI/UX Senior Architect',
      associate_system_engineer: 'Associate System Engineer',
      system_engineer: 'System Engineer',
      senior_system_engineer: 'Senior System Engineer',
      lead_system_engineer: 'Lead System Engineer',
      associate_network_engineer: 'Associate Network Engineer',
      network_engineer: 'Network Engineer',
      senior_network_engineer: 'Senior Network Engineer',
      lead_network_engineer: 'Lead Network Engineer',
      associate_security_engineer: 'Associate Security Engineer',
      security_engineer: 'Security Engineer',
      senior_security_engineer: 'Senior Security Engineer',
      lead_security_engineer: 'Lead Security Engineer',
      associate_devops_engineer: 'Associate Devops Engineer',
      devops_engineer: 'Devops Engineer',
      senior_devops_engineer: 'Senior Devops Engineer',
      lead_devops_engineer: 'Lead Devops Engineer',
      frontend_engineer: 'Frontend Engineer',
      frontend_developer: 'Frontend Developer',
      senior_frontend_engineer: 'Senior Frontend Engineer',
      senior_frontend_developer: 'Senior Frontend Developer',
      associate_security_analyst: 'Associate Security Analyst',
      security_analyst: 'Security Analyst',
      information_security_manager: 'Information Security Manager',
      soc_engineer: 'SOC Engineer',
      technical_trainer: 'Technical Trainer',
      technology_evangelist: 'Technology evangelist',
      senior_functional_consultant: 'Senior Functional Consultant',
      technical_consultant: 'Technical Consultant',
      senior_technical_consultant: 'Senior Technical Consultant',
      manager_it_operation: 'Manager IT Operations',
      dispatch_field_engineer: 'Dispatch/ Field Engineer',
      associate_project_manager: 'Associate Project Manager',
      project_manager: 'Project Manager',
      senior_project_manager: 'Senior Project Manager',
      pmo_manager: 'PMO Manager',
      head_of_delivery: 'Head of Delivery',
      associate_reliability_engineer: 'Associate Reliability Engineer',
      reliability_engineer: 'Reliability Engineer',
      senior_reliability_engineer: 'Senior Reliability Engineer'
    }
  end
end
